// Mock data for admin dashboard preview

export const mockDashboardStats = {
  totalMembers: 247,
  totalActiveMembers: 189,
  totalArtworks: 532,
  totalActiveArtworks: 421,
  pendingRegistrations: 12,
  pendingPurchaseRequests: 8,
  totalRevenue: 284750,
  monthlyRevenue: 42300,
  totalTransactions: 156,
  activeExhibitions: 3,
}

export const mockMembers = [
  {
    id: 1,
    email: 'sarah.johnson@example.com',
    fullName: 'Sarah Johnson',
    role: 'buyer',
    phone: '+1-555-0123',
    isActive: true,
    createdAt: '2024-01-15T10:30:00Z',
    status: 'Pending',
    totalOrders: 0,
    totalSpent: 0,
  },
  {
    id: 2,
    email: 'michael.chen@example.com',
    fullName: 'Michael Chen',
    role: 'seller',
    phone: '+1-555-0124',
    isActive: true,
    createdAt: '2024-01-14T14:20:00Z',
    status: 'Approved',
    totalOrders: 15,
    totalSpent: 12500,
  },
  {
    id: 3,
    email: 'emma.davis@example.com',
    fullName: 'Emma Davis',
    role: 'buyer',
    phone: '+1-555-0125',
    isActive: true,
    createdAt: '2024-01-16T09:15:00Z',
    status: 'Pending',
    totalOrders: 0,
    totalSpent: 0,
  },
  {
    id: 4,
    email: 'james.wilson@example.com',
    fullName: 'James Wilson',
    role: 'seller',
    phone: '+1-555-0126',
    isActive: false,
    createdAt: '2024-01-10T16:45:00Z',
    status: 'Rejected',
    totalOrders: 0,
    totalSpent: 0,
  },
  {
    id: 5,
    email: 'olivia.martinez@example.com',
    fullName: 'Olivia Martinez',
    role: 'buyer',
    phone: '+1-555-0127',
    isActive: true,
    createdAt: '2024-01-12T11:30:00Z',
    status: 'Approved',
    totalOrders: 8,
    totalSpent: 6780,
  },
]

export const mockArtworks = [
  {
    id: 1,
    title: 'Sunset Over Mountains',
    description: 'A breathtaking oil painting capturing the golden hour over mountain ranges.',
    sellerName: 'Michael Chen',
    sellerEmail: 'michael.chen@example.com',
    categoryName: 'Landscape',
    fixedPrice: 1250,
    currency: 'USD',
    status: 'PendingApproval',
    createdAt: '2024-01-15T08:30:00Z',
    primaryImageUrl: '/sunset-mountains-painting.jpg',
    isFor: 'sale',
  },
  {
    id: 2,
    title: 'Abstract Emotions',
    description: 'Modern abstract piece exploring human emotions through bold colors.',
    sellerName: 'Sarah Williams',
    sellerEmail: 'sarah.williams@example.com',
    categoryName: 'Abstract',
    fixedPrice: 850,
    currency: 'USD',
    status: 'Approved',
    createdAt: '2024-01-10T14:20:00Z',
    primaryImageUrl: '/abstract-art-colors.jpg',
    isFor: 'sale',
  },
  {
    id: 3,
    title: 'Urban Life',
    description: 'Contemporary photograph depicting bustling city streets.',
    sellerName: 'David Park',
    sellerEmail: 'david.park@example.com',
    categoryName: 'Photography',
    fixedPrice: 450,
    currency: 'USD',
    status: 'PendingApproval',
    createdAt: '2024-01-16T10:15:00Z',
    primaryImageUrl: '/urban-street-photography.png',
    isFor: 'auction',
  },
  {
    id: 4,
    title: 'Serenity',
    description: 'Minimalist sculpture representing peace and balance.',
    sellerName: 'Lisa Anderson',
    sellerEmail: 'lisa.anderson@example.com',
    categoryName: 'Sculpture',
    fixedPrice: 2100,
    currency: 'USD',
    status: 'Rejected',
    createdAt: '2024-01-08T12:00:00Z',
    primaryImageUrl: '/minimalist-sculpture.png',
    isFor: 'sale',
  },
  {
    id: 5,
    title: 'Coastal Morning',
    description: 'Watercolor depicting a peaceful coastal scene at dawn.',
    sellerName: 'Michael Chen',
    sellerEmail: 'michael.chen@example.com',
    categoryName: 'Watercolor',
    fixedPrice: 680,
    currency: 'USD',
    status: 'Approved',
    createdAt: '2024-01-14T09:30:00Z',
    primaryImageUrl: '/coastal-watercolor.png',
    isFor: 'sale',
  },
]

export const mockTransactions = [
  {
    id: 1,
    userName: 'Olivia Martinez',
    userEmail: 'olivia.martinez@example.com',
    orderNumber: 'ORD-2024-001',
    totalAmount: 1250,
    currency: 'USD',
    paymentType: 'Credit Card',
    status: 'Pending',
    createdAt: '2024-01-16T15:30:00Z',
    orderItems: [
      { artworkTitle: 'Sunset Over Mountains', sellerName: 'Michael Chen', price: 1250 },
    ],
  },
  {
    id: 2,
    userName: 'James Rodriguez',
    userEmail: 'james.rodriguez@example.com',
    orderNumber: 'ORD-2024-002',
    totalAmount: 850,
    currency: 'USD',
    paymentType: 'PayPal',
    status: 'Completed',
    createdAt: '2024-01-15T11:20:00Z',
    orderItems: [{ artworkTitle: 'Abstract Emotions', sellerName: 'Sarah Williams', price: 850 }],
  },
  {
    id: 3,
    userName: 'Emily Brown',
    userEmail: 'emily.brown@example.com',
    orderNumber: 'ORD-2024-003',
    totalAmount: 2780,
    currency: 'USD',
    paymentType: 'Bank Transfer',
    status: 'Pending',
    createdAt: '2024-01-16T09:45:00Z',
    orderItems: [
      { artworkTitle: 'Coastal Morning', sellerName: 'Michael Chen', price: 680 },
      { artworkTitle: 'Serenity', sellerName: 'Lisa Anderson', price: 2100 },
    ],
  },
  {
    id: 4,
    userName: 'Daniel Kim',
    userEmail: 'daniel.kim@example.com',
    orderNumber: 'ORD-2024-004',
    totalAmount: 450,
    currency: 'USD',
    paymentType: 'Credit Card',
    status: 'Completed',
    createdAt: '2024-01-14T16:30:00Z',
    orderItems: [{ artworkTitle: 'Urban Life', sellerName: 'David Park', price: 450 }],
  },
]

export const mockExhibitions = [
  {
    id: 1,
    title: 'Modern Perspectives',
    description: 'Exploring contemporary art through diverse mediums and styles.',
    startDate: '2024-02-01',
    endDate: '2024-03-15',
    location: 'Main Gallery, Floor 2',
    isActive: true,
    totalArtworks: 24,
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 2,
    title: 'Landscapes Reimagined',
    description: 'Traditional and modern interpretations of natural beauty.',
    startDate: '2024-01-15',
    endDate: '2024-02-28',
    location: 'East Wing Gallery',
    isActive: true,
    totalArtworks: 18,
    createdAt: '2024-01-05T14:30:00Z',
  },
  {
    id: 3,
    title: 'Urban Stories',
    description: 'Photography exhibition capturing life in metropolitan areas.',
    startDate: '2023-12-01',
    endDate: '2024-01-31',
    location: 'West Wing Gallery',
    isActive: false,
    totalArtworks: 32,
    createdAt: '2023-11-15T09:00:00Z',
  },
]
