name: Docker Image CI

on:
  push:
    branches: [ "deploy-backend" ]
  pull_request:
    branches: [ "deploy-backend" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./backend/Synos.Api --file ./backend/Dockerfile -t aptech/synos-backend

  push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Tag the image
      run: docker tag aptech/synos-backend:latest 472387458149.dkr.ecr.ap-southeast-1.amazonaws.com/aptech/synos-backend:latest
    - name: Push to AWS repository
      run: docker push 472387458149.dkr.ecr.ap-southeast-1.amazonaws.com/aptech/synos-backend:latest